#!/bin/bash

load inquirer

help() {
  echo "Usage:"
  echo "  zrsvm use"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local current=$(rsvm::current)
  if [ -z "$current" ]; then
    echo "No version is currently set"
    exit 0
  fi

  echo "$current"
}

run() {
  core $@
}

run $@
