#!/bin/bash

help() {
  echo "Usage:"
  echo "  zrsvm ls-remote"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  rsvm::list_remote
}

run() {
  core $@
}

run $@
