#!/bin/bash

load inquirer

help() {
  echo "Usage:"
  echo "  zrsvm remove"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local version=$1

  if [ -z "$version" ]; then
    local availables=($(rsvm::list))
    inquirer::select "Select ?" availables version
  fi

  if [ "$(rsvm::current)" = "$version" ]; then
    local yesno=(No yes)
    inquirer::select "Select ?" yesno confirm
    if [ "$confirm" = "No" ]; then
      exit 0
    fi
  fi

  rsvm::remove $version

  log::success "remove ${version} success"

  if [ -n "$(rsvm::current)" ]; then
    echo "current: $(rsvm::current)"
  fi
}

run() {
  core $@
}

run $@
