#!/bin/bash

# rsvm::install install rust version
rsvm::install() {
  vm::ensure

  # 1. get version (vm::version_parse only use in install)
  local version=$(vm::version_parse $1)
  # 2. get download url
  local url=$(rsvm::internal_install_get_download_url $version)

  # 3. download
  rsvm::internal_install_download $version $url
  # 4. apply local
  rsvm::internal_install_apply_local $version

  # if no current, set current
  if [ "$(rsvm::current)" == "" ]; then
    rsvm::use $version
  else
    # apply env
    rsvm::env
  fi
}

# rsvm::internal_install_get_download_url get download url
rsvm::internal_install_get_download_url() {
  local version=$1
  local os=$(vm::os)
  local arch=$(vm::arch)

  # linux
  # https://static.rust-lang.org/dist/rust-1.60.0-x86_64-unknown-linux-gnu.tar.gz
  # https://static.rust-lang.org/dist/rust-1.60.0-aarch64-unknown-linux-gnu.tar.gz
  #
  # mac
  # https://static.rust-lang.org/dist/rust-1.60.0-x86_64-apple-darwin.tar.gz
  # https://static.rust-lang.org/dist/rust-1.60.0-aarch64-apple-darwin.tar.gz
  #
  if [ "$(net::is_google_visitable)" = "false" ]; then
    PLUGIN_RSVM_RUST_SOURCE=${PLUGIN_RSVM_RUST_SOURCE_CHINA}
  fi

  # force cn mirror
  if [ -n "${FORCE_CN}" ]; then
    PLUGIN_RSVM_RUST_SOURCE=${PLUGIN_RSVM_RUST_SOURCE_CHINA}
  fi

  # custom source
  if [ -n "${RUST_SOURCE}" ]; then
    PLUGIN_RSVM_RUST_SOURCE=$RUST_SOURCE
  fi

  local filename=rust-${version}-${arch}-${os}.tar.gz
  echo ${PLUGIN_RSVM_RUST_SOURCE}/$filename
}

rsvm::internal_install_download() {
  local version=$1
  local tar_gz_url=$2
  if [ -z "$version" ]; then
    log::error "[rsvm::internal_install_download] version is required"
    exit 1
  fi

  if [ -z "$tar_gz_url" ]; then
    log::error "[rsvm::internal_install_download] tar_gz_url is required"
    exit 1
  fi

  # 302 redirect
  curl -I $tar_gz_url 2>/dev/null | head -n 1 | grep "302" >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    local location=$(curl -I $tar_gz_url 2>/dev/null | grep location | awk '{print $2}')

    # fix location
    # stackoverflow: https://stackoverflow.com/questions/70660633/curl-3-url-using-bad-illegal-format-or-missing-url-in-bash-windows
    location=$(echo $location | sed 's/\r//g')

    # 404
    curl -I $location 2>/dev/null | head -n 1 | grep "404" >>/dev/null 2>&1
    if [ "$?" = "0" ]; then
      log::error "[rsvm::install] invalid version: $version"
      log::error "[rsvm::install] see more version at $PLUGIN_RSVM_RUST_SOURCE_OFFICIAL"
      exit 1
    fi
  else
    # 404
    curl -I $tar_gz_url 2>/dev/null | head -n 1 | grep "404" >>/dev/null 2>&1
    if [ "$?" = "0" ]; then
      log::error "[rsvm::install] invalid version: $version"
      log::error "[rsvm::install] see more version at $PLUGIN_RSVM_RUST_SOURCE_OFFICIAL"
      exit 1
    fi
  fi

  # download
  # wget -c $tar_gz_url -O $PLUGIN_RSVM_RUST_DOWNLOAD_TMP
  os::download $PLUGIN_RSVM_RUST_DOWNLOAD_TMP $tar_gz_url
}

rsvm::internal_install_apply_local() {
  local os=$(vm::os)
  local arch=$(vm::arch)

  local version_no_v=$1
  if [ -z "$version_no_v" ]; then
    log::error "[rsvm::internal_install_apply_local] version is required"
    exit 1
  fi

  # add prefix v*
  local version=$(vm::version_ensure_prefix_v $version_no_v)

  # clean old
  if [ -d "$PLUGIN_RSVM_VERSIONS/$version" ]; then
    sudo rm -rf $PLUGIN_RSVM_VERSIONS/$version
  fi
  # decompress
  sudo tar -C $PLUGIN_RSVM_VERSIONS -xzf $PLUGIN_RSVM_RUST_DOWNLOAD_TMP
  # rename
  sudo mv $PLUGIN_RSVM_VERSIONS/rust-${version_no_v}-${arch}-${os} $PLUGIN_RSVM_VERSIONS/$version

  # clean
  sudo rm -f $PLUGIN_RSVM_RUST_DOWNLOAD_TMP
}

export -f rsvm::install

# install internal processes
export -f rsvm::internal_install_get_download_url
export -f rsvm::internal_install_download
export -f rsvm::internal_install_apply_local
